### ISSUE TITLE
.net core & remoting

### ISSUE THREAD

**Issue by benny-gold** [nightroman/Mdbc#20] opened 2018-05-17 22:20 UTC
When running Mdbc in the official [powershell](https://hub.docker.com/r/microsoft/powershell/) docker container: 

`PS> Connect-Mdbc mongodb://localhost issue issue -NewCollection`

```Connect-Mdbc : Could not load type 'System.Runtime.Remoting.Messaging.CallContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.```

This is a [problem with .net core](https://github.com/dotnet/core/issues/223) rather than the Mdbc module but thought I'd log this for posterity. 
I'll take a swing at porting to dotnet if I get some time but you might already be looking at it.

cheers

**Comment by nightroman** [comment] 2018-05-18 00:47
I am not looking at .NET Core yet. But as the first step in this direction, I am going to convert the project to .NET SDK.

**Comment by nightroman** [comment] 2018-05-18 18:38
It turns out to be easier than I thought. I will soon release a version with latest C# driver and the project converted to .NET SDK.

But I also already have a version built for netstandard2.0 and it seems to be working (needs more testing). It works in PS Core, too, so the issue is presumably resolved.

Should we switch to netstandard2.0 completely? That's the question. It means PS 5+ only.

**Comment by nightroman** [comment] 2018-05-20 03:37
The branch **master** is converted to .NET SDK.

The new branch **180520-netcore** builds the module for `netstandard2.0`. It would be nice if you can build and play with it on PS Core. If all if fine we'll of how to proceed.

**Comment by nightroman** [comment] 2018-05-20 09:35
The latest **master** supports both net45 and netstandard2.0.
**180520-netcore** was removed.

**Comment by benny-gold** [comment] 2018-05-20 13:55
You're awesome. I'm not familiar with `Invoke-Build` so not sure if I'm calling it correctly in [this Dockerfile](https://github.com/benny-gold/Mdbc/blob/master/Dockerfile) - can you point me in the right direction please?

**Comment by nightroman** [comment] 2018-05-20 14:02
It does not seem quite right. But I am not quite sure what you are trying to do. Let me know exactly.
Please note that building of the module is currently designed for Windows only.

**Comment by nightroman** [comment] 2018-05-20 14:11
I am not planning to make building x-plat. I do not need this.
Here is the net-core module for you to play.
[Mdbc.zip](https://github.com/nightroman/Mdbc/files/2020375/Mdbc.zip)

**Comment by nightroman** [comment] 2018-06-19 18:20
I close this issue for now. At some point, we probably need to decide how to proceed. Perhaps we should just switch to net-core version. The later the better, indeed.

**Closed by nightroman** 2018-06-19 18:20 UTC

**Comment by nightroman** [comment] 2018-10-01 12:03
@Gitii Thank you for the good news.

**Comment by shaneis** [comment] 2019-04-19 11:22
Just chiming in here that I had the same set-up and the same issue as well.
The .zip file worked (incentive to release it for the future 😉  )

**Comment by nightroman** [comment] 2019-04-20 05:23
The question is, should it be a separate package/module or just one net-core version?
Net-core seems to be working with PS v5 but I am not sure about v3, v4...

**Comment by nightroman** [comment] 2019-04-21 05:03
For now I am going to add `Mdbc-net-core.zip` to releases, e.g. see the latest v5.1.5:
https://github.com/nightroman/Mdbc/releases/tag/v5.1.5
